version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "forum_db"
      POSTGRES_USER: "root"
      POSTGRES_HOST: "localhost"
      POSTGRES_PASSWORD: "love"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped